# Generated by Django 5.1.6 on 2025-02-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("location", models.CharField(max_length=150)),
                ("location_tips", models.CharField(max_length=150)),
                ("call_for_direction", models.CharField(max_length=30)),
                ("is_free", models.BooleanField(default=True)),
            ],
        ),
    ]
