# Generated by Django 5.1.6 on 2025-02-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="country",
            field=models.CharField(
                choices=[
                    ("nigeria", "Nigeria"),
                    ("ghana", "Ghana"),
                    ("usa", "United States of America"),
                ],
                default="nigeria",
                max_length=15,
            ),
        ),
    ]
