# Generated by Django 5.1.6 on 2025-02-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_event_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("chidren", "Children & Youth"),
                    ("fashion", "Fashion & Design"),
                    ("media", "Media & Gym"),
                    ("sport", "Sport & Fitness"),
                    ("government", "Government"),
                    ("community", "Community"),
                    ("charity", "Charity & Aid"),
                    ("school", "School & Education"),
                    ("career", "Career"),
                    ("spirituality", "Spirituality & Religion"),
                    ("investments", "Investments"),
                    ("business", "Business"),
                    ("technology", "Technology & Science"),
                    ("startups", "Startups & Small Business"),
                    ("foods", "Foods & Drink"),
                    ("art", "Art & Culture"),
                    ("music", "Music & Performance"),
                ],
                default="business",
                max_length=50,
            ),
        ),
    ]
